// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liqvmgbqphhesualxxtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcXZtZ2JxcGhoZXN1YWx4eHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjQ4MzMsImV4cCI6MjA1ODI0MDgzM30.jO2wlfGpB4TnC6rbyVxAUxnnsMXvBLYTYpJ87v7vCDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);